export const enum ActionKind {
    SEARCH_USERS = "SEARCH_USERS",
    CLEAR_USERS = "CLEAR_USERS",
    GET_USERS_REPOS = "GET_USERS_REPOS",
    GET_USERS = "GET_USERS",
    CHANGE_DARK_MODE = "CHANGE_DARK_MODE",
    CLEAR_REPOS = "CLEAR_REPOS",
    CLEAR_MORE_DETAILS = "CLEAR_MORE_DETAILS",
}
// 9b71c6d6d91a51eefa13
// 016939a710efc111e6af45a88eb3b8ad0e55c0e2
