export const enum ActionKind {
    SEARCH_USERS = "SEARCH_USERS",
    CLEAR_USERS = "CLEAR_USERS",
    GET_USERS_REPOS = "GET_USERS_REPOS",
    GET_USERS = "GET_USERS",
    CHANGE_DARK_MODE = "CHANGE_DARK_MODE",
    CLEAR_REPOS = "CLEAR_REPOS",
    CLEAR_MORE_DETAILS = "CLEAR_MORE_DETAILS",
}
